"""empty message

Revision ID: 01c0edd9bf4d
Revises: 
Create Date: 2023-12-31 11:16:58.116664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01c0edd9bf4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_registrations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('NOT_VERIFIED', 'VERIFIED', 'STAGING', 'SCHEDULED', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', collation='utf8mb4_general_ci'),
               type_=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'STAGING', 'SCHEDULED', 'CANCELED', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', name='medicalregistrationstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_registrations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('NOT_VERIFIED', 'VERIFIED', 'STAGING', 'SCHEDULED', 'CANCELED', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', name='medicalregistrationstatus'),
               type_=mysql.ENUM('NOT_VERIFIED', 'VERIFIED', 'STAGING', 'SCHEDULED', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', collation='utf8mb4_general_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
