"""empty message

Revision ID: 0539b7753acc
Revises: 5398380457d8
Create Date: 2024-01-02 11:49:47.497021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0539b7753acc'
down_revision = '5398380457d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=False)

    # ### end Alembic commands ###
