"""empty message

Revision ID: 4008dbe8eca7
Revises: ed1298cf6e09
Create Date: 2023-11-25 08:36:22.009126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4008dbe8eca7'
down_revision = 'ed1298cf6e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
