"""empty message

Revision ID: 412ccb79689e
Revises: 589f0f36fcef
Create Date: 2023-12-29 08:02:29.284300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412ccb79689e'
down_revision = '589f0f36fcef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_schedules', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
