"""empty message

Revision ID: 5f09dc97b033
Revises: 02026d970d22
Create Date: 2023-11-25 10:20:59.488521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f09dc97b033'
down_revision = '02026d970d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=11),
               nullable=False)

    # ### end Alembic commands ###
