"""empty message

Revision ID: 633967eb7aa1
Revises: fa82ad2a32e7
Create Date: 2024-01-07 19:15:26.982707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633967eb7aa1'
down_revision = 'fa82ad2a32e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['medical_examination_id'])

    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['medical_registration_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
