"""empty message

Revision ID: 71c27f9947ed
Revises: 1d8ff1e3c6b9
Create Date: 2024-01-04 19:41:19.939907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c27f9947ed'
down_revision = '1d8ff1e3c6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advice', sa.UnicodeText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.drop_column('advice')

    # ### end Alembic commands ###
