"""empty message

Revision ID: 89afdcd62f08
Revises: 6b3741bbb87d
Create Date: 2024-01-03 11:53:01.382092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89afdcd62f08'
down_revision = '6b3741bbb87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint('bills_ibfk_4', type_='foreignkey')
        batch_op.drop_column('policy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False))
        batch_op.create_foreign_key('bills_ibfk_4', 'policies', ['policy'], ['id'])

    # ### end Alembic commands ###
