"""empty message

Revision ID: 8eaee6a1f597
Revises: 01c0edd9bf4d
Create Date: 2024-01-01 08:55:17.906561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eaee6a1f597'
down_revision = '01c0edd9bf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfilled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.drop_column('fulfilled')

    # ### end Alembic commands ###
