"""empty message

Revision ID: af3616f356e2
Revises: 
Create Date: 2024-01-07 09:24:05.077294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af3616f356e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('EXAMINATION_FEE', 'NUMBER_OF_PATIENTS', name='policytype'), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
