"""empty message

Revision ID: b987ea4ab530
Revises: da564fcb90ed
Create Date: 2023-12-30 10:20:41.382145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b987ea4ab530'
down_revision = 'da564fcb90ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('NOT_VERIFIED', 'VERIFIED', 'NOT_SCHEDULED', 'SCHEDULED', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', name='medicalregistrationstatus'), nullable=True))
        batch_op.drop_column('fulfilled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfilled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
