"""empty message

Revision ID: bfcae88209fe
Revises: 633967eb7aa1
Create Date: 2024-01-07 20:21:10.572743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfcae88209fe'
down_revision = '633967eb7aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index('medical_examination_id')
        batch_op.drop_constraint('bills_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'medical_examinations', ['id'], ['id'])
        batch_op.drop_column('medical_examination_id')

    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.drop_index('medical_registration_id')
        batch_op.drop_constraint('medical_examinations_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'medical_registrations', ['id'], ['id'])
        batch_op.drop_column('medical_registration_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_registration_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('medical_examinations_ibfk_2', 'medical_registrations', ['medical_registration_id'], ['id'])
        batch_op.create_index('medical_registration_id', ['medical_registration_id'], unique=False)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_examination_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bills_ibfk_2', 'medical_examinations', ['medical_examination_id'], ['id'])
        batch_op.create_index('medical_examination_id', ['medical_examination_id'], unique=False)

    # ### end Alembic commands ###
