"""empty message

Revision ID: cfd9d3c866bd
Revises: 78008b9debd5
Create Date: 2023-12-21 17:52:02.238224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfd9d3c866bd'
down_revision = '78008b9debd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))

    # ### end Alembic commands ###
