"""empty message

Revision ID: da564fcb90ed
Revises: 412ccb79689e
Create Date: 2023-12-29 08:29:36.511413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da564fcb90ed'
down_revision = '412ccb79689e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_schedules', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
