"""empty message

Revision ID: dfdc477ead35
Revises: 8eaee6a1f597
Create Date: 2024-01-02 00:09:59.775621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfdc477ead35'
down_revision = '8eaee6a1f597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.drop_column('symptom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptom', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False))

    # ### end Alembic commands ###
