"""empty message

Revision ID: ed1298cf6e09
Revises: 675b6a172b1d
Create Date: 2023-11-23 10:23:07.992243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed1298cf6e09'
down_revision = '675b6a172b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examination_detail', schema=None) as batch_op:
        batch_op.alter_column('dosage',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               type_=sa.UnicodeText(),
               existing_nullable=False)

    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.alter_column('symptom',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.UnicodeText(),
               existing_nullable=False)
        batch_op.alter_column('diagnosis',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.UnicodeText(),
               existing_nullable=False)

    with op.batch_alter_table('medical_registrations', schema=None) as batch_op:
        batch_op.alter_column('symptom',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.UnicodeText(),
               existing_nullable=True)

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.UnicodeText(),
               existing_nullable=True)

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.UnicodeText(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.UnicodeText(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.UnicodeText(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=True)

    with op.batch_alter_table('medical_registrations', schema=None) as batch_op:
        batch_op.alter_column('symptom',
               existing_type=sa.UnicodeText(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=True)

    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=sa.UnicodeText(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=False)
        batch_op.alter_column('symptom',
               existing_type=sa.UnicodeText(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=False)

    with op.batch_alter_table('medical_examination_detail', schema=None) as batch_op:
        batch_op.alter_column('dosage',
               existing_type=sa.UnicodeText(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
