"""empty message

Revision ID: f49405f77407
Revises: adcbca9d98e0
Create Date: 2024-01-02 11:00:53.785233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49405f77407'
down_revision = 'adcbca9d98e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('symptom', sa.UnicodeText(), nullable=True),
    sa.Column('date_of_visit', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('NOT_VERIFIED', 'VERIFIED', 'STAGING', 'SCHEDULED', 'CANCELED', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', name='medicalregistrationstatus'), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_schedule_id'], ['appointment_schedules.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'medical_registrations', ['medical_registration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_examinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('medical_registrations')
    # ### end Alembic commands ###
