"""empty message

Revision ID: f9461d84a5f9
Revises: 0e1d271616a9
Create Date: 2023-12-02 05:47:02.410638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9461d84a5f9'
down_revision = '0e1d271616a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=False)

    # ### end Alembic commands ###
